import {createClient} from "@/lib/supabase/server";
import {saveSettings,recordMemberRefund,deleteMemberRefund} from "./actions";
import Modal from "@/components/Modal";
import ConfirmSubmitButton from "@/components/ConfirmSubmitButton";
const money=(n:number)=>`KES ${new Intl.NumberFormat("en-KE").format(n)}`;
const memberNo=(v:unknown)=>Number(String(v??"").replace(/\D/g,""))||Number.MAX_SAFE_INTEGER;
export default async function Settings(){const s=await createClient();const [{data:r},{data:memberData},{data:refunds}]=await Promise.all([s.from("settings").select("*").limit(1).single(),s.from("members").select("id,membership_no,full_name,status").is("deleted_at",null),s.from("member_refunds").select("id,amount,refund_date,reason,reference,members(membership_no,full_name)").is("deleted_at",null).order("refund_date",{ascending:false})]);const members=[...(memberData||[])].sort((a:any,b:any)=>memberNo(a.membership_no)-memberNo(b.membership_no));const refundForm=<form action={recordMemberRefund}><div className="formgrid"><div className="field"><label>Member</label><select name="member_id" required><option value="">Select member</option>{members.map((m:any)=><option key={m.id} value={m.id}>{m.membership_no} — {m.full_name} ({m.status})</option>)}</select></div><div className="field"><label>Refund Amount (KES)</label><input name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Refund Date</label><input name="refund_date" type="date" required/></div><div className="field"><label>Reference</label><input name="reference"/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>Reason</label><input name="reason" defaultValue="Contribution refund on withdrawal"/></div></div><div className="notice" style={{marginTop:14}}>This keeps the member's original contributions in history, records the cash refund separately, and marks the member Withdrawn.</div><button className="btn success">Record Refund</button></form>;
return <><div className="pagehead"><div><h1>Settings & Administration</h1><p className="muted">Manage CWMS business rules and controlled financial corrections without changing historical transactions.</p></div></div>
<div className="panel" style={{marginBottom:18}}><h3>Financial Rules</h3><form action={saveSettings}><div className="formgrid"><div className="field"><label>Monthly Contribution</label><input name="monthly_contribution" type="number" min="0" step="0.01" defaultValue={Number(r?.monthly_contribution||500)}/></div><div className="field"><label>Registration Fee</label><input name="registration_fee" type="number" min="0" step="0.01" defaultValue={Number(r?.registration_fee||1500)}/></div><div className="field"><label>Loan Interest %</label><input name="loan_interest_rate" type="number" min="0" step="0.01" defaultValue={Number(r?.loan_interest_rate||0.10)>1?Number(r?.loan_interest_rate):Number(r?.loan_interest_rate||0.10)*100}/></div><div className="field"><label>Repayment Months</label><input name="repayment_period_months" type="number" min="1" defaultValue={r?.repayment_period_months||3}/></div><div className="field"><label>Financial Year</label><input name="financial_year" type="number" defaultValue={r?.financial_year||2026}/></div><div className="field"><label>Opening Cash Balance</label><input name="opening_cash_balance" type="number" step="0.01" defaultValue={Number(r?.opening_cash_balance||0)}/></div><div className="field"><label>Contribution Due Day</label><input name="contribution_due_day" type="number" min="1" max="31" defaultValue={r?.contribution_due_day||28}/></div><div className="field"><label>Monthly Report Title</label><input name="report_title" defaultValue={r?.report_title||"Chyun Welfare Monthly Statement"}/></div></div><div className="checkgrid"><label><input type="checkbox" name="include_registration_in_cash" defaultChecked={Boolean(r?.include_registration_in_cash)}/> Include registration fees in fund cash</label><label><input type="checkbox" name="include_outstanding_interest_in_fund" defaultChecked={Boolean(r?.include_outstanding_interest_in_fund)}/> Include outstanding interest in Total Fund Value</label></div><button className="btn success" style={{marginTop:14}}>Save Settings</button></form></div>
<div className="panel"><div className="pagehead"><div><h3 style={{margin:0}}>Member Withdrawal & Contribution Refunds</h3><p className="muted">Use this instead of deleting contributions when money is returned to a withdrawing member.</p></div><Modal trigger="+ Record Contribution Refund" title="Record Member Contribution Refund">{refundForm}</Modal></div><div className="tablewrap"><table><thead><tr><th>Date</th><th>Member</th><th>Amount</th><th>Reason</th><th>Reference</th><th>Action</th></tr></thead><tbody>{refunds?.length?refunds.map((x:any)=><tr key={x.id}><td>{x.refund_date}</td><td>{x.members?.membership_no} — {x.members?.full_name}</td><td>{money(Number(x.amount))}</td><td>{x.reason||"-"}</td><td>{x.reference||"-"}</td><td><form action={deleteMemberRefund}><input type="hidden" name="id" value={x.id}/><ConfirmSubmitButton message="Reverse/delete this refund record? The Audit Log will retain the action."/></form></td></tr>):<tr><td colSpan={6} className="empty">No contribution refunds recorded.</td></tr>}</tbody></table></div></div>
<div className="notice" style={{marginTop:18}}><strong>What Settings can change:</strong> contribution amount, registration fee, interest rate for new loans, repayment period, report options, due day and controlled refund/correction records. New modules, page redesigns and software bugs still require a code update.</div></>}
