"use server";import {createClient} from "@/lib/supabase/server";import {revalidatePath} from "next/cache";import {z} from "zod";
const S=z.object({loan_id:z.string().uuid(),amount:z.coerce.number().positive(),payment_date:z.string().min(1),receipt_no:z.string().optional()});
export async function recordRepayment(fd:FormData){const p=S.parse({loan_id:fd.get("loan_id"),amount:fd.get("amount"),payment_date:fd.get("payment_date"),receipt_no:fd.get("receipt_no")||undefined});const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("Not authenticated");
const {data:profile}=await s.from("profiles").select("organization_id").eq("id",user.id).single();const {data:loan,error:le}=await s.from("loans").select("*").eq("id",p.loan_id).single();if(le||!loan)throw new Error("Loan not found");
let remaining=p.amount;const interestPaid=Math.min(remaining,Number(loan.outstanding_interest));remaining-=interestPaid;const principalPaid=Math.min(remaining,Number(loan.outstanding_principal));remaining-=principalPaid;
const newInterest=Number(loan.outstanding_interest)-interestPaid;const newPrincipal=Number(loan.outstanding_principal)-principalPaid;const status=(newInterest<=0&&newPrincipal<=0)?"cleared":(new Date(loan.due_date)<new Date()?"overdue":"active");
const {data:item,error}=await s.from("repayments").insert({organization_id:profile!.organization_id,loan_id:p.loan_id,amount:p.amount,interest_paid:interestPaid,principal_paid:principalPaid,payment_date:p.payment_date,receipt_no:p.receipt_no,entered_by:user.id}).select("id").single();if(error)throw new Error(error.message);
await s.from("loans").update({outstanding_interest:newInterest,outstanding_principal:newPrincipal,status,updated_at:new Date().toISOString()}).eq("id",p.loan_id);
await s.from("audit_logs").insert({organization_id:profile!.organization_id,user_id:user.id,action:"repayment.created",module:"repayments",entity_id:item.id,description:`KES ${p.amount}; interest ${interestPaid}; principal ${principalPaid}`});revalidatePath("/app/repayments");revalidatePath("/app/loans");revalidatePath("/app")}
